version: '3.9'

services:
  web:
    build: .
    container_name: shop_backend_app
    volumes:
      - ./logs:/app/logs
    ports:
      - "5555:5555"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - API_UPDATE_INTERVAL=${API_UPDATE_INTERVAL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: shop_backend_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
